name: Build and deploy Node.js app to Azure Web App - findmyflight-backend-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build backend (NestJS)
      - name: Build backend
        run: npm run build

      # 5️⃣ Run tests (optional)
      - name: Run tests
        run: npm run test --if-present

      # 6️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F850CA7351DF4C2E82AC3256A54575A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0C44E09FA88E42D0801C0FFF8FD57EA5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_771198733EDE4DB9886877826CBA073B }}

      # 7️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'findmyflight-backend-prod'
          slot-name: 'Production'
          package: .